### ISSUE TITLE
App has no page verification

### ISSUE THREAD

**Issue by Katacka** [upcs/cs-341-project-sq19-foxtrot#188]
Steps to recreate:
1. Visit the page
2. Enter http://35.203.183.149:3000/MAIN_GUI.html as the url 

It doesn't appear that you have any security enabled to prevent a user from "signing in" by simply visiting http://35.203.183.149:3000/MAIN_GUI.html. This could be fixed by generating a Session_ID post sign in and checking the Session_ID each page visit, prior to sending any assets.

**Comment by ashika-m** [comment]
Thanks for pointing this out! We'll work on it.
