### ISSUE TITLE
Add habit with more than one word

### ISSUE THREAD

**Issue by huymn** [upcs/cs-341-project-sq19-foxtrot#190]
I added "chicken wings" as a habit but on the table it says "undefined" for the new habit that I just added

**Comment by ashika-m** [comment]
Habits with multiple words do work. This may be an issue with trying to add when the server is down, or not marking it as completed before leaving the page which someone else mentioned. Thank you for pointing this out.

**Comment by ashika-m** [comment]
Fixed
