### ISSUE TITLE
Can't see new journal entry

### ISSUE THREAD

**Issue by maloney20** [upcs/cs-341-project-sq19-foxtrot#192]
recreate:
1. create new journal entry
2. submit 
3. select 'previous weeks'

You should probably be able to see the entry that you just submitted, but it's not there

**Comment by schibel21** [comment]
Thank you for finding this issue! This might have occurred with multiple people on the server at the same time, which can cause posting issues, but I'll take a look into it! Thank you for telling us about this issue! :)
