### ISSUE TITLE
Splash page CSS doesn't work well on smaller screens

### ISSUE THREAD

**Issue by ghost** [upcs/cs-341-project-sq19-foxtrot#193]
![foxtrot](https://user-images.githubusercontent.com/31501005/55893311-dc2c5800-5b6c-11e9-85ea-8387b721c0b3.PNG)

My screen resolution is 1366x768

**Comment by schibel21** [comment]
Thank you for finding this issue! We have noticed this issue with our CSS and plan on fixing it so the text stays the same size no matter the screen size. Thank you so much for telling us about this! :)

**Comment by schibel21** [comment]
We adjusted the calculations and are sure that this does work on other smaller screens. Thank you!
