### ISSUE TITLE
Extended Journal Entry isn't Extended

### ISSUE THREAD

**Issue by vogtl19** [upcs/cs-341-project-sq19-foxtrot#194]
Recreate: 

1. Log into Polina's Account (had Los Angeles Theme)
2. Go to Extended Journal
3. Typed: This is a test for the extended journal. This is a test for the extended journal. This is a test for the extended journal. This is a test for the extended journal. This is a test for the extended journal. This is a test for the extended journal. This is a test for the extended journal. This is a test for the extended journal. This is a test for the extended journal. This is a test for the extended journal. This is a test for the extended journal. This is a test for the extended journal. 
 - This is 96 characters and it worked.
4. Typed the same thing with 101 words and it did not display in "previous weeks

**Comment by schibel21** [comment]
Thank you for finding this issue! I have gotten it to work before, but there may be a bug of some kind that I might have missed and it may be acting funky with multiple people on the same server. I'll take a look at it! Thank you so much for telling us about this! :)
