### ISSUE TITLE
Un-click complete habit not available

### ISSUE THREAD

**Issue by jayazicate** [upcs/cs-341-project-sq19-foxtrot#195]
Should be able to unclick complete just in case someone accidentally clicks the button without completing their habit for the day. Have a popup saying 'are you sure you've completed this habit?' to double check too. Also just a suggestion: add rewards whenever habits are completed for the week :)

**Comment by hoangj21** [comment]
Yes I agree that it should be an option for the user to unclick their habits, we'll put that on our todo list. To your suggestion- we'd love to implement that, we're planning on maybe having a congratulations pop up if the user completes a streak of habits.

**Comment by ashika-m** [comment]
Since this was not in the original scope of our project we have decided not to implement this enhancement.
