### ISSUE TITLE
Broke Server: Too long of Habit Tracker Entry

### ISSUE THREAD

**Issue by vogtl19** [upcs/cs-341-project-sq19-foxtrot#199]
Recreate: 

1. Go to Habit Tracker
2. Entered the Habit: How many characters can fit in this text field? I wonder if it too many will break it :/
3. Site changes to 404 Site Not Found (in the url is the title of my habit with "+" between characters)

**Comment by hoangj21** [comment]
You might be right, too many characters in the text field might break it, since we didn't set a character limit.

**Comment by ashika-m** [comment]
Fixed!
